import { CredentialType, LLMModel } from "@prisma/client";

export enum ModelProvider {
  OPENAI = "OpenAI",
  ANTHROPIC = "Anthropic",
  GOOGLE = "Google",
  GROQ = "Groq",
  AWS_BEDROCK = "AWS Bedrock",
}

export interface ModelMetadata {
  provider: ModelProvider;
  display: string;
  enum: LLMModel;
  value: string;
  contextLength: number;
  weight: number,
  isImageInputSupported: boolean;
  requiredCredentialForLtdUsers: CredentialType;
  requiredCredentialForEveryoneElse: CredentialType | null;
  relatedCredentialList: CredentialType[];
  tooltipContent?: string;
}

export const MODEL_LIST: ModelMetadata[] = [
  // OPENAI
  {
    provider: ModelProvider.OPENAI,
    display: "GPT-4o Mini",
    enum: LLMModel.GPT_4O_MINI,
    value: "gpt-4o-mini",
    contextLength: 128000,
    weight: 1,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.OPENAI_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Good for almost all tasks",
    relatedCredentialList: [CredentialType.OPENAI_API_KEY],
  },
  {
    provider: ModelProvider.OPENAI,
    display: "GPT-4o",
    enum: LLMModel.GPT_4_VISION_PREVIEW,
    value: "gpt-4o",
    contextLength: 128000,
    weight: 10,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.OPENAI_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Good for almost all tasks",
    relatedCredentialList: [CredentialType.OPENAI_API_KEY],
  },
  {
    provider: ModelProvider.OPENAI,
    display: "GPT-4 Turbo",
    enum: LLMModel.GPT_4_TURBO,
    value: "gpt-4-turbo",
    contextLength: 128000,
    weight: 20,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.OPENAI_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Good for almost all tasks",
    relatedCredentialList: [CredentialType.OPENAI_API_KEY],
  },
  // ANTHROPIC
  {
    provider: ModelProvider.ANTHROPIC,
    display: "Claude 3.5 Sonnet",
    enum: LLMModel.CLAUDE_35_SONNET,
    value: "claude-3-5-sonnet-20240620",
    contextLength: 200000,
    weight: 10,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.ANTHROPIC_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Best for creative writing & coding tasks",
    relatedCredentialList: [CredentialType.ANTHROPIC_API_KEY],
  },
  {
    provider: ModelProvider.ANTHROPIC,
    display: "Claude 3 Haiku",
    enum: LLMModel.CLAUDE_3_HAIKU_20240307,
    value: "claude-3-haiku-20240307",
    contextLength: 200000,
    weight: 1,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.ANTHROPIC_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Good for creative writing & coding tasks",
    relatedCredentialList: [CredentialType.ANTHROPIC_API_KEY],
  },
  {
    provider: ModelProvider.ANTHROPIC,
    display: "Claude 3 Sonnet",
    enum: LLMModel.CLAUDE_3_SONNET_20240229,
    value: "claude-3-sonnet-20240229",
    contextLength: 200000,
    weight: 10,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.ANTHROPIC_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Good for creative writing & coding tasks",
    relatedCredentialList: [CredentialType.ANTHROPIC_API_KEY],
  },
  {
    provider: ModelProvider.ANTHROPIC,
    display: "Claude 3 Opus",
    enum: LLMModel.CLAUDE_3_OPUS_20240229,
    value: "claude-3-opus-20240229",
    contextLength: 200000,
    weight: 50,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.ANTHROPIC_API_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Good for creative writing & coding tasks",
    relatedCredentialList: [CredentialType.ANTHROPIC_API_KEY],
  },
  // GOOGLE
  {
    provider: ModelProvider.GOOGLE,
    display: "Gemini 1.5 Pro",
    enum: LLMModel.GOOGLE_GEMINI_PRO,
    value: "models/gemini-1.5-pro-latest",
    contextLength: 1000000,
    weight: 5,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.GOOGLE_GENAI_API_KEY,
    requiredCredentialForEveryoneElse: CredentialType.GOOGLE_GENAI_API_KEY,
    tooltipContent: "Good for working with documents & long-form writing",
    relatedCredentialList: [CredentialType.GOOGLE_GENAI_API_KEY],
  },
  {
    provider: ModelProvider.GOOGLE,
    display: "Gemini 1.5 Flash",
    enum: LLMModel.GOOGLE_GEMINI_FLASH,
    value: "models/gemini-1.5-flash-latest",
    contextLength: 1000000,
    weight: 1,
    isImageInputSupported: true,
    requiredCredentialForLtdUsers: CredentialType.GOOGLE_GENAI_API_KEY,
    requiredCredentialForEveryoneElse: CredentialType.GOOGLE_GENAI_API_KEY,
    tooltipContent: "Good for working with documents & long-form writing",
    relatedCredentialList: [CredentialType.GOOGLE_GENAI_API_KEY],
  },
  // GROQ
  {
    provider: ModelProvider.GROQ,
    display: "LLaMA 3.1 70b",
    enum: LLMModel.GROQ_LLAMA_3_70B,
    value: "llama-3.1-70b-versatile",
    contextLength: 128000,
    weight: 1,
    isImageInputSupported: false,
    requiredCredentialForLtdUsers: CredentialType.GROQ_API_KEY,
    requiredCredentialForEveryoneElse: CredentialType.GROQ_API_KEY,
    tooltipContent: "Cost-effective & Good for tasks that don't require knowledge sources",
    relatedCredentialList: [CredentialType.GROQ_API_KEY],
  },
  {
    provider: ModelProvider.GROQ,
    display: "LLaMA 3.1 8b",
    enum: LLMModel.GROQ_LLAMA_3_8B,
    value: "llama-3.1-8b-instant",
    contextLength: 128000,
    weight: 1,
    isImageInputSupported: false,
    requiredCredentialForLtdUsers: CredentialType.GROQ_API_KEY,
    requiredCredentialForEveryoneElse: CredentialType.GROQ_API_KEY,
    tooltipContent: "Cost-effective & Good for tasks that don't require knowledge sources",
    relatedCredentialList: [CredentialType.GROQ_API_KEY],
  },
  // AWS BEDROCK
  {
    provider: ModelProvider.AWS_BEDROCK,
    display: "LLaMA 3.1 70b",
    enum: LLMModel.AWS_BEDROCK_META_LLAMA_3_70B,
    value: "meta.llama3-1-70b-instruct-v1:0",
    contextLength: 128000,
    weight: 3,
    isImageInputSupported: false,
    requiredCredentialForLtdUsers: CredentialType.AWS_SECRET_ACCESS_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Cost-effective & Good for tasks that don't require knowledge sources",
    relatedCredentialList: [CredentialType.AWS_ACCESS_KEY_ID, CredentialType.AWS_SECRET_ACCESS_KEY],
  },
  {
    provider: ModelProvider.AWS_BEDROCK,
    display: "LLaMA 3.1 8b",
    enum: LLMModel.AWS_BEDROCK_META_LLAMA_3_8B,
    value: "meta.llama3-1-8b-instruct-v1:0",
    contextLength: 128000,
    weight: 0.2,
    isImageInputSupported: false,
    requiredCredentialForLtdUsers: CredentialType.AWS_SECRET_ACCESS_KEY,
    requiredCredentialForEveryoneElse: null,
    tooltipContent: "Cost-effective & Good for tasks that don't require knowledge sources",
    relatedCredentialList: [CredentialType.AWS_ACCESS_KEY_ID, CredentialType.AWS_SECRET_ACCESS_KEY],
  },
]
